import { Inter } from "next/font/google";
import "./globals.css";
import AuthStateChangeProvider from "../../context/auth";
import { UserProvider } from "../../context/user";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Netflix - next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <AuthStateChangeProvider>{children}</AuthStateChangeProvider>
        </UserProvider>
      </body>
    </html>
  );  
}
